clair:
  database:
    type: pgsql
    options:
      source: postgresql://postgres:password@postgres:5432?sslmode=disable
      cachesize: 16384
  api:
    port: 6060
    healthport: 6061
    timeout: 900s
  updater:
    interval: 2h
  notifier:
    attempts: 3
    renotifyinterval: 2h
